INSERT INTO USER (ID, NAME, PHONE) VALUES (1,'Sunjyot Singh', 9876543210);

INSERT INTO CAB (ID, OCCUPIED, XAXIS, YAXIS) VALUES (1,false,1,1);
INSERT INTO CAB (ID, OCCUPIED, XAXIS, YAXIS) VALUES (2,false,9,9);